
import "./globals.css";
import Navbar from "./component/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className=' w-full font-clash overflow-x-hidden relative'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
